version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${DATASOURCE_NAME}
      POSTGRES_USER: ${DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${DATASOURCE_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    ports:
      - "8081:8080"

  authapi:
    image: authapi:latest
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db

  tests:
    image: authapi:latest
    env_file:
      - .env
    depends_on:
      - db
    command: [ "./gradlew", "test" ]

volumes:
  pgdata:


